blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://forums.yogstation.net/index.php?forums/feature-requests.221/
    about: Feature requests are not handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums here --> 
